### ISSUE TITLE
onClose event

### ISSUE THREAD

**Issue by Izrab** [proyecto26/nativescript-inappbrowser#12]
Does this plugin provide an onClose event? 
I want to execute some code when the user closes the inAppBrowser. **How?**

**Comment by jdnichollsc** [comment]
```
 if (await InAppBrowser.isAvailable()) {
  const result = await InAppBrowser.open(url)
  // HERE...
}
```

**Comment by FlawaCLV** [comment]
@jdnichollsc is it possible to "bubble up" an event? I would like to trigger `InAppBrowser.close()` from the browser. Is it possible?

Basic exemple: I make a simple action in my browser page then I want to close my InAppBrowser.

**Comment by jdnichollsc** [comment]
you can do that with a deep linking redirection from browser:
- Configuring deep linking: https://github.com/proyecto26/nativescript-inappbrowser#authentication-flow-using-deep-linking
- Redirecting with that deep linking url: https://github.com/proyecto26/react-native-inappbrowser/blob/gh-pages/index.html#L56
