### ISSUE TITLE
Feature request:  Ability to open with html string instead of URL.

### ISSUE THREAD

**Issue by pandralouis** [proyecto26/nativescript-inappbrowser#13]
The Nativescript WebView component allows passing either a URL or a string containing html content.  It's sometimes necessary to build an html string and open it, and this would allow this plugin to be used instead of the WebView component where that is necessary.

Thanks for the great plugin!

**Comment by jdnichollsc** [comment]
**SafariViewController** only support http and https schemes as you can see here => https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/1621222-initwithurl?language=objc
