### ISSUE TITLE
How to detect when in app browser is closed?

### ISSUE THREAD

**Issue by syahnur197** [proyecto26/nativescript-inappbrowser#23]
I want to navigate the user to different screen once they close the browser. As of now I'm using version 1.0.2 because this is the only version my app can use. Thanks

**Comment by jdnichollsc** [comment]
And what's the problem here?

**Comment by syahnur197** [comment]
thank you very much it works!

**Comment by syahnur197** [comment]
a different issue this time. I notice some apps does not prompt the user what browser they want to use when they open a link to in app browser. However this one, the user is prompted what browser they want to use. Is there a way where I can default the browser programmatically without prompting the user whay browser they want to use? 

The app I'm referring to is

https://play.google.com/store/apps/details?id=nz.co.vista.android.movie.themallcineplex

you can see the in app browser during checkout

**Comment by jdnichollsc** [comment]
Hi Syahnur,
Please, check the docs of Chrome Custom Tabs and let me know if you can see any example to select only the default browser, also please open another issue for this.

Thanks!
