### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses' android

### ISSUE THREAD

**Issue by bunower** [proyecto26/nativescript-inappbrowser#24]
Hey Folks,
after updatign nativescript to 6.3.3 i cant get it work on android.
i get following errror:

`Execution failed for task ':app:checkDebugDuplicateClasses'.
Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)
Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.`

### Which platform(s) does your issue occur on?
- Android
- emulator and device. 

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.3.3
- Cross-platform modules: (check the 'version' attribute in the
- `node_modules/tns-core-modules/package.json`  6.3

The error comes, whe i try to build android.

iOS works like charm

**Comment by jdnichollsc** [comment]
Do you have any repo in order to reproduce this issue? :)

**Comment by bunower** [comment]
> Do you have any repo in order to reproduce this issue? :)

Sorry i didnt have a public repo...
Can i give you some other information?

**Comment by jdnichollsc** [comment]
Yes please, because I don't understand the issue

**Comment by bunower** [comment]
Hey,
i created a repository for you.
[repo](https://github.com/bunower/nativescript-inappbrowser-firebase)
After investigating a little bit, i found out, the problem occurs not on a fresh install. Only in combination with [firebase-plugin](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) for nativescript.
If you set in `firebase.nativescript.json` to
`"messaging": true,
  "in_app_messaging": true,`
you got the error.
I checked boths `include.gradle` files.
**firebase-plugin:**
`
android {
    // (possibly-temporary) workaround for https://stackoverflow.com/questions/52518378/more-than-one-file-was-found-with-os-independent-path-meta-inf-proguard-android
    packagingOptions {
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://maven.google.com"
    }
    jcenter()
}

dependencies {
    def supportVersion = project.hasProperty("supportVersion") ? project.supportVersion : "26.1.0"
    def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : "16.0.1"

    if (googlePlayServicesVersion != '+' && org.gradle.util.VersionNumber.parse(googlePlayServicesVersion) < org.gradle.util.VersionNumber.parse('15.0.+')) {
        throw new GradleException(" googlePlayServicesVersion set too low, please update to at least 15.0.0 / 15.0.+ (currently set to $googlePlayServicesVersion)");
    }

    implementation "com.android.support:appcompat-v7:$supportVersion"
    implementation "com.android.support:cardview-v7:$supportVersion"
    implementation "com.android.support:customtabs:$supportVersion"
    implementation "com.android.support:design:$supportVersion"
    implementation "com.android.support:support-compat:$supportVersion"

    // make sure you have these versions by updating your local Android SDK's (Android Support repo and Google repo)

    // implementation "com.google.firebase:firebase-analytics:17.2.1"

    // for reading google-services.json and configuration
    implementation "com.google.android.gms:play-services-base:$googlePlayServicesVersion"

    // Authentication
    // implementation "com.google.firebase:firebase-auth:19.1.0"

    // Realtime DB
    // implementation "com.google.firebase:firebase-database:19.2.0"

    // Cloud Firestore
    // implementation "com.google.firebase:firebase-firestore:21.3.0"

    // Remote Config
    // implementation "com.google.firebase:firebase-config:19.0.3"

    // Performance Monitoring
    // implementation "com.google.firebase:firebase-perf:19.0.2"

    // Crashlytics
    // implementation "com.crashlytics.sdk.android:crashlytics:2.10.1"

    // Cloud Messaging (FCM)
         implementation "com.google.firebase:firebase-messaging:20.0.1"

    // // implementation "me.leolin:ShortcutBadger:1.1.22@aar"

    // In-App Messaging
    implementation "com.google.firebase:firebase-inappmessaging-display:19.0.2"
    // Analytics seems to be required for In-App Messaging
    // implementation "com.google.firebase:firebase-analytics:17.2.1"

    // Cloud Storage
    // implementation "com.google.firebase:firebase-storage:19.1.0"

    // Cloud Functions
    // implementation "com.google.firebase:firebase-functions:19.0.1"

    // AdMob / Ads
    // implementation "com.google.firebase:firebase-ads:18.3.0"

    // ML Kit
    // implementation "com.google.firebase:firebase-ml-vision:24.0.1"
    // implementation "com.google.firebase:firebase-ml-vision-image-label-model:19.0.0"
    // implementation "com.google.firebase:firebase-ml-vision-object-detection-model:19.0.3"
    // implementation "com.google.firebase:firebase-ml-model-interpreter:22.0.1"
    // implementation "com.google.firebase:firebase-ml-vision-automl:18.0.3"
    // implementation "com.google.firebase:firebase-ml-natural-language:22.0.0"
    // implementation "com.google.firebase:firebase-ml-natural-language-language-id-model:20.0.7"
    // implementation "com.google.firebase:firebase-ml-natural-language-translate-model:20.0.7"
    // implementation "com.google.firebase:firebase-ml-natural-language-smart-reply-model:20.0.7"

    // Facebook Authentication
    // implementation "com.facebook.android:facebook-core:5.4.0"
    // implementation "com.facebook.android:facebook-login:5.4.0"

    // Google Sign-In Authentication
    // implementation "com.google.android.gms:play-services-auth:$googlePlayServicesVersion"

    // Dynamic Links
    // implementation "com.google.firebase:firebase-dynamic-links:19.0.0"
}

apply plugin: "com.google.gms.google-services"

// Crashlytics
//apply plugin: "io.fabric"
`
**InAppBrowser**
/* Include.gradle configuration: http://docs.nativescript.org/plugins/plugins#includegradle-specification */

android {
	
}

dependencies {

    def supportLibVersion = null
    if (project.hasProperty('supportLibVersion')) {
        supportLibVersion = project.supportLibVersion
    } else if (project.hasProperty('supportVersion')) {
        supportLibVersion = project.supportVersion
    }
    if (supportLibVersion) {
        implementation "com.android.support:customtabs:$supportLibVersion"
    } else {
        def androidXBrowser = "1.+"
        if (project.hasProperty('androidXBrowser')) {
            androidXBrowser = project.androidXBrowser
        }
        implementation "androidx.browser:browser:$androidXBrowser"
    }
}`
`
Thanks for helping

**Comment by bunower** [comment]
Any Progress here?

**Comment by jdnichollsc** [comment]
I have been very busy, I will try to check this weekend

**Comment by jdnichollsc** [comment]
Sorry, we can't verify another plugins

**Comment by alejoCandamil** [comment]
Hi, any update with this?
I only have `"messaging": true` in `firebase.nativescript.json` from [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) and i got the same trouble on Android.
Nativescript: 6.5.0
"nativescript-inappbrowser": "^2.3.0"
"nativescript-plugin-firebase": "^10.5.2"

**Comment by ovaltechnologiesinc** [comment]
@alejoCandamil Use the @nativescript/firebase plugin instead. The challenge has been resolved there.
