### ISSUE TITLE
Application fails to start when upgraded from nativescript 6.2.2 to 6.5.0

### ISSUE THREAD

**Issue by krunal-thakur** [proyecto26/nativescript-inappbrowser#27]
### Which platform(s) does your issue occur on?
- iOS (Fails to Build)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules:
  tns-core-modules : 6.5.0
- Runtime(s): 
  tns-android : 6.5.0
  tns-ios : 6.5.0
- Plugin(s): 2.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Application fails on startup with following error on iOS

NativeScript caught signal 11.
Native Stack:
1   0x10818a251 sig_handler(int)
2   0x7fff51bf5b5d _sigtramp
3   0x7fff51c2a71a libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister(bool)
4   0x7fff51c29b85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff51c2de58 _Unwind_RaiseException
6   0x7fff4f9fcad3 __cxa_rethrow
7   0x7fff50b97cb4 objc_exception_rethrow
8   0x7fff50b98f50 initializeNonMetaClass
9   0x7fff50b994ba initializeAndMaybeRelock(objc_class*, objc_object*, mutex_tt<false>&, bool)
10  0x7fff50ba3a5d lookUpImpOrForward
11  0x7fff50b94219 _objc_msgSend_uncached
12  0x7fff50bac5ce +[NSObject new]
13  0x108b7ba8d ffi_call_unix64
14  0x110aeb950
JS Stack:
new([native code])
at ../node_modules/nativescript-inappbrowser/InAppBrowser.js(file: node_modules/nativescript-inappbrowser/InAppBrowser.ios.js:226:0)
at __webpack_require__(file: src/webpack/bootstrap:753:0)
at fn(file: src/webpack/bootstrap:120:0)

**Comment by jdnichollsc** [comment]
Let me update the version of the demo

**Comment by jdnichollsc** [comment]
Check the last version 2.3.0 and let me know 👍

**Comment by krunal-thakur** [comment]
> Check the last version 2.3.0 and let me know 👍

I will check tomorrow and confirm. Thank You.
