### ISSUE TITLE
Should enableUrlBarHiding work in the same manner as enableBarCollapsing ?

### ISSUE THREAD

**Issue by jcassidyav** [proyecto26/nativescript-inappbrowser#30]
### Which platform(s) does your issue occur on?
- Android
- emulator and device.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s):
tns-android : 6.5.0
tns-ios : 6.5.0
- Plugin(s): 2.3.0

### Please, tell us how to recreate the issue in as much detail as possible. 
I am calling InAppBrowser.open with the property enableUrlBarHiding: false,
Should this prevent the url from being hidden when you scroll down the page on android, in the same manner as enableBarCollapsing: false in IOS, or am I misunderstanding the property?

**Comment by jdnichollsc** [comment]
I'm not sure because iOS overview is missing here https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/configuration/2887469-barcollapsingenabled

**Comment by jcassidyav** [comment]
what happens in IOS is that the url/done buttone etc stays visible at the top of the screen when you scroll down the page when enableBarCollapsing = false.

Should that also be the case in android, i.e. the URL bar always remain visible? ( it doesn't for me, it gets hidden if I scroll down the page )

**Comment by jdnichollsc** [comment]
That's the native behavior of both platforms, but any pull request is welcome!

**Comment by jdnichollsc** [comment]
Also, this configuration is only applied with iOS >= 11 as you can see here https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/InAppBrowser.ios.ts#L99
