### ISSUE TITLE
openAuth isn't working as expected

### ISSUE THREAD

**Issue by VinayakNivalkar** [proyecto26/nativescript-inappbrowser#31]
### Which platform(s) does your issue occur on?
- Android
- Android pie
- emulator pixel 3 | API LEVEL 28

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): 6.5.0
- Framework: nativescript-vue 2.6.1

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
1. i am using the module openAuth for Google sign in
2. the module even gives a success response but the app crashes right after the response

### Is there any code involved? 
// the block of code where all starts breaking
async onLogin() {
    const deepLink = application-deeplink
    const url = `https://my-auth-login-page.com?redirect_uri=${deepLink}`
    try {
        InAppBrowser.openAuth(url, deepLink, {
          // iOS Properties
          ephemeralWebSession: false,
          // Android Properties
          showTitle: false,
          enableUrlBarHiding: true,
          enableDefaultShare: false
        }).then((response) => {
          if (
            response.type === 'success' &&
            response.url
          ) {
            Linking.openURL(response.url)
          }
        })
    } catch (error) {
      Linking.openURL(url)
    }
  }

### console logs
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to resume activity {com.package/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onActivityResumed failed
System.err: TypeError: Cannot read property 'resumeWithUrl' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to resume activity {app.pocketnerd/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onActivityResumed failed
System.err: TypeError: Cannot read property 'resumeWithUrl' of undefined
System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4052)
System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4089)
System.err:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1978)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:232)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7172)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onActivityResumed failed
System.err: TypeError: Cannot read property 'resumeWithUrl' of undefined
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.gen.android.app.Application_ActivityLifecycleCallbacks.onActivityResumed(Application_ActivityLifecycleCallbacks.java:32)
System.err:     at android.app.Application.dispatchActivityResumed(Application.java:261)
System.err:     at android.app.Activity.onResume(Activity.java:1397)
System.err:     at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:514)
System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
System.err:     at android.app.Activity.performResume(Activity.java:7467)
System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4044)
System.err:     ... 11 more

**Comment by jdnichollsc** [comment]
Please attach a demo to be able to reproduce this issue

**Comment by VinayakNivalkar** [comment]
I figured it out
There was another oauth dependency(nativescript-outh2) that was interfering with the redirect URI
It works fine without the dependency

**Comment by jdnichollsc** [comment]
Ohh thanks for let me know! Maybe it's because of this => https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/utils.android.ts#L40
We added that validation to avoid issues getting the same previous response of that redirection

**Comment by mtmarco87** [comment]
Hi guys,

@VinayakNivalkar you saved me! I was struggling searching the cause of:
1) TypeError: Cannot read property 'resumeWithUrl' of undefined [...]
2) in alternance with: TypeError: Cannot read property 'toString' of null System.err: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581) [...]

And yes it was a conflict with nativescript-oauth2.

@jdnichollsc I understand the need of this validation. 
Can I suggest you something? Maybe it'd be a good idea to mention this potential issue in the README.md of the project to avoid other people's despair. 
You could notify the conflict when using this plugin together with nativescript-oauth2 and if you want you can mention also the displayed error messages.

Thank you!

**Comment by jdnichollsc** [comment]
@mtmarco87 any pull request is welcome! 🙂

**Comment by jdnichollsc** [comment]
A better option would be if they include InAppBrowser as a dependency https://github.com/alexziskind1/nativescript-oauth2/issues/80

**Comment by mtmarco87** [comment]
> A better option would be if they include InAppBrowser as a dependency [alexziskind1/nativescript-oauth2#80](https://github.com/alexziskind1/nativescript-oauth2/issues/80)

Hi Juan,
maybe the other day I sounded a bit rude, but of course thank you as well, your work is outstanding.
Anyway for your 1st suggestion about the pull-request on the readme, as soon as I will have time I will try to issue a PR.

For what concern the addition of InAppBrowser as a dependency of nativescript-oauth2, it would be great.
Just imagine that although ns-oauth2 is covering all the standard "direct" oauth2 flow with the main providers, it's not covering at all (or at least I wasn't able to find a solution for it) the scenario in which you want to re-use your existing backend already performing oauth2 authentication and jwt-session token generation (in my case spring boot social login).

Using InAppBrowser openAuth this became easily doable. So it would just be great to extend the overall possibilities of the oauth2 library.

Thx again,
Marco

**Comment by jdnichollsc** [comment]
No problem mate, it would be awesome if you can put that comment in the other repository, in that issue I shared in my previous comment, thanks for sharing that! 👍

**Comment by mtmarco87** [comment]
> No problem mate, it would be awesome if you can put that comment in the other repository, in the issue I shared in my previous comment, thanks for sharing that! 👍

Sure man! Let's try to conquer OAuth2 :D I've seen that it's maintained directly by the main contributor of NativeScript, so it'll be really good.

I'm going to post my comment there ;)

**Comment by jdnichollsc** [comment]
@VinayakNivalkar I fixed that problem for the next release here: https://github.com/proyecto26/nativescript-inappbrowser/pull/46/files#diff-7e96f7b14909450a876e532c2adc12455255bcc5d6c8f6ca3c503a32c947a47aL37

Thanks for your ideas!
