### ISSUE TITLE
communication nativescript <-> browser app

### ISSUE THREAD

**Issue by ray007** [proyecto26/nativescript-inappbrowser#33]
This is maybe not exactly the right place to ask, feel free to point me to the right place.

Is there any way to establish communication between the nativescript app and the js-app in the opened browser tab?
Assuming both know about each other.

**Comment by jdnichollsc** [comment]
If you need communication, you need to use a WebView instead

**Comment by ray007** [comment]
I would, if WebViews worked with self-signed certificates.

**Comment by jdnichollsc** [comment]
More details here:
- https://stackoverflow.com/questions/59740313/using-postmessage-in-a-chrome-custom-tabs-customtabssession
- https://stackoverflow.com/questions/35164505/sfsafariviewcontroller-interacting-with-the-parent-app-from-a-web-page

**Comment by ray007** [comment]
Thanks for the information, even though it does not look very promising.
Seems if there is a way to do it now, a custom url scheme would be the way to go. Will need to learn more about that...

**Comment by jdnichollsc** [comment]
Check the **openAuth** method and the redirection using a deep linking (custom url scheme) 🙂
