### ISSUE TITLE
OpenAuth: can change the size of the popup

### ISSUE THREAD

**Issue by uderline** [proyecto26/nativescript-inappbrowser#34]
Hi !

I didn't manage to find information so that's why I'm opening an issue.

### Device
- iPad 7th generation (iOS 13)

### Project version
- CLI: 6.6.0-2020-03-12-100308-14143
- Cross-platform modules: `"version": "6.5.12"`
- Runtimes: both android and iOS are *6.5.0*
- Plugins:
```
"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nativescript/angular": "~9.0.0",
    "@nativescript/theme": "~2.3.0",
    "nativescript-inappbrowser": "^2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~9.1.0",
    "@ngtools/webpack": "~9.1.0",
    "nativescript-dev-webpack": "~1.5.0",
    "tns-platform-declarations": "~6.5.0",
    "typescript": "~3.8.3"
  }
```
### Details
I use the auth0 website and I'm using the inappbrowser. No issues in the functionnalities and quite easy to put in place so thanks guys ! 

Although, I'm not sure about something. When using the `.open()` function, it seems to open in full screen but when using the `.openAuth()` function, it opens as a small centered square.

![image](https://user-images.githubusercontent.com/10776690/89101730-dd893000-d402-11ea-8a94-0dac5d8f5b4c.png)

I went through the code - I'm certainly not an expert (please don't judge me, I come from PHP) - and I didn't find any options referring to the available ones for `.open()`. Basically, I'm looking for a *fullScreen* option for the `.openAuth()` function or a workaround ?

### Sample code
**.ts**
```
async start() {
        if (await InAppBrowser.isAvailable()) {
            InAppBrowser.openAuth('http://google.com', 'http://google.com', {
                modalEnabled: true,
                modalPresentationStyle: 'fullScreen'
            });
        }
    }
```
**.html**
```
<StackLayout>
    <Button (tap)="start()" text="Start"></Button>
</StackLayout>
```

Thanks !

**Comment by jdnichollsc** [comment]
Hi Joseph, we're using **ASWebAuthenticationSession** for iOS, check more info here: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

**Comment by uderline** [comment]
Ok so I guess that it's just - as I thought - technically impossible, thanks for your help ! 
Would it be worth adding the available options dedicated to each call in the readme ?

**Comment by jdnichollsc** [comment]
Any pull request is always welcome!
