### ISSUE TITLE
Cannot read property 'MajorVersion' of undefined

### ISSUE THREAD

**Issue by FlawaCLV** [proyecto26/nativescript-inappbrowser#41]
### The issue occurs on :
- iOS 14
- Emulator & device
- CLI: 7.0.9-rc.0

"dependencies": {
        "@nativescript/core": "^7.0.5",
        "@nativescript/webpack": "3.0.4",
        "@nota/nativescript-webview-ext": "^7.0.0",
        "axios": "^0.20.0",
        "date-fns": "^2.10.0",
        "nativescript-audio": "^6.1.0",
        "nativescript-carousel": "^7.0.1",
        "nativescript-email": "^1.6.0",
        "nativescript-feedback": "^2.0.0",
        "nativescript-google-analytics": "^0.4.4",
        "nativescript-inappbrowser": "^2.2.0",
        "nativescript-insomnia": "^2.0.0",
        "nativescript-iqkeyboardmanager": "^1.5.1",
        "nativescript-modal-datetimepicker": "^1.2.2",
        "nativescript-onesignal": "^1.0.8",
        "nativescript-orientation": "^2.2.3",
        "nativescript-purchase": "^2.0.13",
        "nativescript-rater": "^2.1.1",
        "nativescript-sentry": "^2.0.0",
        "nativescript-social-share": "^1.6.0",
        "nativescript-socket.io": "^0.11.1",
        "nativescript-status-bar": "^1.2.0",
        "nativescript-vibrate": "^4.0.1",
        "nativescript-videoplayer": "^5.0.1",
        "nativescript-vue": "2.8.1",
        "nativescript-vue-star-rating": "^0.0.5",
        "underscore": "^1.9.2",
        "vuex": "^3.1.2"
    },
    "devDependencies": {
        "@babel/core": "~7.11.6",
        "@babel/preset-env": "~7.11.5",
        "@nativescript/android": "7.0.0",
        "@nativescript/ios": "7.0.0",
        "babel-loader": "~8.1.0",
        "nativescript-vue-template-compiler": "2.8.1",
        "node-sass": "^4.13.1",
        "vue-loader": "~15.9.0"
    },

The app crashes at launch with this following error :

`(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'MajorVersion' of undefined
at
../node_modules/nativescript-inappbrowser/InAppBrowser.js(file: node_modules/nativescript-inappbrowser/InAppBrowser.ios.js:35:28)`

**Comment by jdnichollsc** [comment]
We're checking some issues before to publish a new version to support last version of NativeScript, but I'm busy until October 1st, so please wait

**Comment by lukasjuhas** [comment]
#40 Will fix this.

**Comment by lukasjuhas** [comment]
@FlawaCLV #40 will fix this.

**Comment by jdnichollsc** [comment]
Please check here https://github.com/proyecto26/nativescript-inappbrowser/pull/40#issuecomment-705674217
