### ISSUE TITLE
Access to the URL on InAppBrowser

### ISSUE THREAD

**Issue by GMatshwane** [proyecto26/nativescript-inappbrowser#43]
Do we have a way of access the URL parameters? The initial URL that I open the InAppBrowser with actually redirects me to another page where I need to access the queryParams. Is there a way of access the the URL params with this plugin?

**Comment by jdnichollsc** [comment]
Are you using **openAuth** method?

**Comment by GMatshwane** [comment]
Yes I am

**Comment by jdnichollsc** [comment]
I mean, with the url of that redirection you can use another npm package to extract these params

**Comment by GMatshwane** [comment]
I managed to get the redirect going. Thanks
