### ISSUE TITLE
Getting {type: "dismiss"} after authentication on Android

### ISSUE THREAD

**Issue by GMatshwane** [proyecto26/nativescript-inappbrowser#45]
Opening and Authenticating using the InAppBrowser works fine - using **openAuth**. 
The issue is after authentication, the app closes. When opening it again, I get {'type': 'dismiss','message':'Chrome tabs activity destroyed'}.

**Comment by jdnichollsc** [comment]
Let me debug with the new version we're trying to publish ASAP

**Comment by wellingWilliam** [comment]
I would like to second this issue. Using openAuth for iOS works perfectly, but Android does not. Testing with Facebook, LinkedIn, and Google proxied by a service. The redirect is to the service via https, then redirects to the app by schema, host, and path. I have read that best practice is to bind the context/intent with a CustomTabsClient and invoke warmup.

**Comment by wellingWilliam** [comment]
I have found the incompatibility with using a proxy redirect back to the app. The `redirectUrl` fails checks by `startsWith` as it is not the original redirect url. i.e. `https://foo.bar/callback?code=123&state=abc => 301 location schema://host/callback?code=123&state=abc`

https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/utils.android.ts#L51
https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/utils.android.ts#L87

I do not know if this is the cause as the original issue, but resulted in the same symptom. I would like to hear suggestions regarding this or will I have to work from a forked version? I'd rather not and would hope there is an elegant solution worth incorporating in this library. Thanks.

**Comment by jdnichollsc** [comment]
Do you know if this works to get that url? https://reactnative.dev/docs/linking#getinitialurl

**Comment by wellingWilliam** [comment]
As it turns out, I do not have an issue at all. The `returnUrl` passed into `openAuth` is merely for validating the redirect from the original URL.  I simply had to pass the anticipated app URL as `returnUrl` and both iOS and Android work as expected. Sorry for hijacking this issue. In terms of debugging the original issue, I think double checking `AndroidManifest.xml` intent-filter, use `android:launchMode="singleInstance"` for the activity and probably most important set InAppBrowser option `forceCloseOnRedirection: true`.

**Comment by GMatshwane** [comment]
@wellingWilliam I will have a try. Thanks

**Comment by wwelling** [comment]
@jdnichollsc I have begun testing on newer versions of Android and found Android API 27 Google Authentication hangs.  The redirect to Google sign-in works and upon successful login, the progress bar spins and never returns to the app and doesn't log anything.  Both Facebook and LinkedIn work so this may be a difference between OpenId and standard OAuth. I am hoping later API versions work but it is more and more difficult to remount to update the etc hosts file.

**Comment by jdnichollsc** [comment]
I'm moving some fixes before to publish a new release, during the week is complicated for me (Because I'm not working with NativeScript, it's really just a hobby without sponsors), I'm trying to do that for this weekend :)

**Comment by jdnichollsc** [comment]
Can you help me to debug the last changes from `develop` branch? There's a PR for the next release: https://github.com/proyecto26/nativescript-inappbrowser/pull/46

**Comment by jdnichollsc** [comment]
Please try the last version 3.0.0 👍
