### ISSUE TITLE
AndroidX compatibility (Cannot read property 'Builder' of undefined)

### ISSUE THREAD

**Issue by sulymkaa** [proyecto26/nativescript-inappbrowser#5]
please add androidx compatibility

    <StackLayout>
        <Button text="test inappbrowser" (tap)="testBrowser()"></Button>
    </StackLayout>

    async testBrowser() {
        const url = 'https://www.google.com'
        if (await InAppBrowser.isAvailable()) {
            const result = await InAppBrowser.open(url)
            alert({
            title: 'Response',
            message: JSON.stringify(result),
            okButtonText: 'Ok'
            })
        }
    }

Android platform while calling InAppBrowser throw error:

JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'Builder' of undefined
JS: TypeError: Cannot read property 'Builder' of undefined
JS:     at Object.push.../node_modules/nativescript-inappbrowser/InAppBrowser.js.InAppBrowserModule.open (file:///data/data/org.nativescript.inappBrowserTest/files/app/vendor.js:80447:44)
JS:     at ItemsComponent.<anonymous> (file:///data/data/org.nativescript.inappBrowserTest/files/app/bundle.f10a611c2a8d3c767d72.hot-update.js:38:111)
JS:     at step (file:///data/data/org.nativescript.inappBrowserTest/files/app/vendor.js:127752:23)
JS:     at Object.next (file:///data/data/org.nativescript.inappBrowserTest/files/app/vendor.js:127733:53)
JS:     at fulfilled (file:///data/data/org.nativescript.inappBrowserTest/files/app/vendor.js:127723:58)
JS:     at ZoneDelegate.push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke (file:///data/data/org.nativescript.inappBrowserTest/files/app/vendor.js:78754:26)

here is the steps to create new project and reproduce issue:

tns create [<App Name>] --ng
cd [<App Name>]
tns plugin add nativescript-inappbrowser
tns platform add android@androidx
npm i tns-core-modules@androidx
tns run android -- bundle

  "nativescript": {
    "id": "org.nativescript.inappBrowserTest",
    "tns-android": {
      "version": "6.0.0-2019-06-05-002854-01"
    }
  }
  "dependencies": {
      "@angular/...":  "~8.0.0",
      "nativescript-angular": "~8.0.0", 
      "nativescript-inappbrowser": "^1.0.2",
      ...
      "tns-core-modules": "^5.4.0-androidx-2019-03-22-160602-06",
  }

tns --version   5.4.2
Angular CLI: 8.0.6
Node: 10.16.0
npm 6.9.0
OS: darwin x64
Angular: 8.0.3

**Comment by jdnichollsc** [comment]
let me check, thanks mate!

**Comment by jdnichollsc** [comment]
@sulymkaa do you know if you can use jetifier to fix that? I want to avoid breaking changes :/

**Comment by jdnichollsc** [comment]
Nevermind, that only works for native code directly 😅

**Comment by tgpetrov** [comment]
Actually, plugins can support androidx without braking changes. There is a "Make it Compatible with Both Support-lib and AndroidX" section in [this blog post](https://www.nativescript.org/blog/migrating-nativescript-plugins-to-androidx).

**Comment by sulymkaa** [comment]
@jdnichollsc would you be able to make update according to migration post?

**Comment by jdnichollsc** [comment]
Let me see tomorrow 👍

**Comment by jdnichollsc** [comment]
ok guys, I'm going to publish a new version with other changes, let me do that at night 👍

**Comment by sulymkaa** [comment]
@jdnichollsc , could you please let me know when you are going to push an update please?

**Comment by adfdev** [comment]
for the moment have migrate in [this tool](https://github.com/NativeScript/androidx-migration-tool) folder in node_modules

**Comment by jdnichollsc** [comment]
Sorry for the delay guys, yesterday I had an accident in my motorcycle, let me do this today 👍

**Comment by jdnichollsc** [comment]
guys, do you know if I can avoid breaking changes by doing this from `include.gradle`?
```
dependencies {
    def supportLibVersion = null
    if (project.hasProperty('supportLibVersion')) {
        supportLibVersion = project.supportLibVersion
    } else if (project.hasProperty('supportVersion')) {
        supportLibVersion = project.supportVersion
    }
    if (supportLibVersion) {
      implementation "com.android.support:customtabs:$supportLibVersion"
    } else {
      implementation 'androidx.browser:browser:1.+'
    }
}
```

**Comment by sulymkaa** [comment]
@jdnichollsc , I tried to do it, but nothing has changed( are you ok after your bike accident?

**Comment by jdnichollsc** [comment]
Hi guys, please check the last changes from the demo of this repo and also, let me know what you think about this configuration https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/platforms/android/include.gradle#L14

**Comment by jdnichollsc** [comment]
@sulymkaa thanks for asking, I'm feel better 😅

**Comment by tgpetrov** [comment]
@jdnichollsc The configuration looks good.
However, I believe [this line](https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/InAppBrowser.android.ts#L30) can break the backwards compatibility. Maybe you can use the CustomTabsIntent const that you creating on the next line, instead of hardcoding the androidx.browser.customtabs.CustomTabsIntent path?

**Comment by jdnichollsc** [comment]
Ohh but it's only for types, how can you create a type using a variable? 🤔

**Comment by jdnichollsc** [comment]
You can see the types of both here https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/types/android.d.ts

**Comment by tgpetrov** [comment]
Aah, I see. Yes, you are right, should be ok the way it is now.

**Comment by jdnichollsc** [comment]
Cool, I only have a little issue I want to fix before to publish the new version of the plugin... I want to be able to disable the animation when the SafariViewController is closed but I don't know how to do that, here https://github.com/proyecto26/nativescript-inappbrowser/blob/master/src/InAppBrowser.ios.ts#L189

Any help is really appreciated 😅

**Comment by sulymkaa** [comment]
@jdnichollsc could you please tell me how I can build this myself to test, or may be you can email me builded archive? Thanks!

**Comment by jdnichollsc** [comment]
mmm ok I'm going to publish the new version now, maybe the animation issue is a bug of the **SafariViewController** and I can fix that later as a minor change

**Comment by jdnichollsc** [comment]
Guys, I need help to fix the build issues in order to publish the new version, any help is really appreciated 👍

**Comment by jdnichollsc** [comment]
Done! https://github.com/proyecto26/nativescript-inappbrowser/releases/tag/v2.0.0
