### ISSUE TITLE
Browser in android (IsAvailable returning false)

### ISSUE THREAD

**Issue by uderline** [proyecto26/nativescript-inappbrowser#53]
Hi !

I'm testing my app on Android and it seems like the in-app browser doesn't work whereas on iOS it works like a charm.

`await InAppBrowser.isAvailable()` always return *false* on android.

Just in case, I tested the demo app (master) on an emulator Pixel 3 (API 30) and it still doesn't work.

```
async openLink() {
    try {
      const { url } = this;
      console.log(await InAppBrowser.isAvailable()); // Returns false
      if (await InAppBrowser.isAvailable()) {
        const result = await InAppBrowser.open(url, {
          // iOS Properties
          dismissButtonStyle: 'cancel',
          ....
       });
    ....
```

So I was wondering if it was a bug, my emulator or am I just missing something ?

Thanks,

**Comment by jdnichollsc** [comment]
Try linking manually :)

**Comment by jdnichollsc** [comment]
Hello Joseph, what do you think about this validation? https://github.com/proyecto26/nativescript-inappbrowser/blob/develop/src/InAppBrowser.android.ts#L81

**Comment by uderline** [comment]
So, I checked and made some tests.

I understand the purpose of the function and sort of how it works (I'm not a native android/iOS developer).

If you do:
```ts
isAvailable() {
      return true;
      // const context = Utils.android.getApplicationContext();
      // const resolveInfos = getPreferredPackages(context);
      // return Promise.resolve(!(resolveInfos === null || resolveInfos.isEmpty()));
}
```

It will work and a custom tab will be displayed ... So I guess there is something wrong on this line `const resolveInfos = getPreferredPackages(context);`.

Do you reproduce the behavior ? I'm still trying to find a fix to this issue (on my spare time so it could take some time ...). If you have any idea ?

**Comment by jdnichollsc** [comment]
I'm not sure, it's odd because here it's working as expected: https://github.com/proyecto26/react-native-inappbrowser/blob/develop/android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java#L207

**Comment by Caluminus** [comment]
I've had the same issue, but only when I updated my phone to Android 11. Google have changed the way custom tabs are launched: https://developers.google.com/web/updates/2020/07/custom-tabs-android-11

Like @uderline I've replaced the `isAvailable()` contents with `return true;` and it has fixed it. Obviously not robust though.

**Comment by jcassidyav** [comment]
> I've had the same issue, but only when I updated my phone to Android 11. Google have changed the way custom tabs are launched: https://developers.google.com/web/updates/2020/07/custom-tabs-android-11

Reading through that doc, the other option appears to be to add a queries section to the AndroidManifest
i.e.

```
  <queries>
    <intent>
        <action android:name=
            "android.support.customtabs.action.CustomTabsService" />
    </intent>
  </queries>
```

This appears to allow the exiting code to work.  Any downsides to this ?

**Comment by uderline** [comment]
> > I've had the same issue, but only when I updated my phone to Android 11. Google have changed the way custom tabs are launched: https://developers.google.com/web/updates/2020/07/custom-tabs-android-11
> 
> Reading through that doc, the other option appears to be to add a queries section to the AndroidManifest
> i.e.
> 
> ```
>   <queries>
>     <intent>
>         <action android:name=
>             "android.support.customtabs.action.CustomTabsService" />
>     </intent>
>   </queries>
> ```
> 
> This appears to allow the existing code to work. Any downsides to this ?

This is definitely the solution ! Just added it to the AndroidManifest and it works - no other modifications.

**Comment by jdnichollsc** [comment]
Hello folks, please check the new version [3.1.0](https://github.com/proyecto26/nativescript-inappbrowser/releases/tag/v3.1.0) 👍
