### ISSUE TITLE
DeepLinking redirect to app not working

### ISSUE THREAD

**Issue by BrothersWar** [proyecto26/nativescript-inappbrowser#62]
### Which platform(s) does your issue occur on?
Android Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.2.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s):   "dependencies": {
    "@angular/animations": "10.0.0",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "10.0.0",
    "@angular/compiler": "10.0.0",
    "@angular/core": "10.0.0",
    "@angular/fire": "^6.0.0",
    "@angular/forms": "10.0.0",
    "@angular/material": "^9.2.1",
    "@angular/platform-browser": "10.0.0",
    "@angular/platform-browser-dynamic": "10.0.0",
    "@angular/router": "10.0.0",
    "@nativescript/angular": "10.0.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/theme": "~2.5.0",
    "angular-material": "^1.1.21",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "firebase": "^7.14.2",
    "nativescript-audio": "^6.2.1",
    "nativescript-inappbrowser": "^3.0.2",
    "nativescript-remote-builds": "^1.1.1",
    "ng-circle-progress": "^1.5.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "6.6.0",
    "tslib": "^1.10.0",
    "zone.js": "0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1000.8",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "10.0.0",
    "@angular/language-service": "~9.1.1",
    "@nativescript/android": "7.0.1",
    "@nativescript/schematics": "^11.0.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/webpack": "~3.0.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^3.8.3"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
When i try deeplinking there is 1 sec load when i press PRESS HERE TO REDIRECT and then nothing happens.

AndroidManifest:
```
	<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
	</intent-filter>
	<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="my-demo" android:host="demo"  android:scheme="http"/>
	</intent-filter>
```
deep link function:
```
  async onLogin() {
    const deepLink = getDeepLink('home')
    const loginUrl = `https://proyecto26.github.io/react-native-inappbrowser`
    const url = `${loginUrl}?redirect_url=${encodeURIComponent(deepLink)}`;
    try {
      if (await InAppBrowser.isAvailable()) {
        InAppBrowser.openAuth(url, deepLink, {
          // iOS Properties
          ephemeralWebSession: false,
          // Android Properties
          showTitle: false,
          enableUrlBarHiding: true,
          enableDefaultShare: false
        }).then((response) => {
          console.log( response)
          if (
            response.type === 'success' &&
            response.url
          ) {
            Utils.openUrl(response.url)
          }
        })
      } else Utils.openUrl(url)
    } catch (error) {
      Utils.openUrl(url)
    }
  }
```
utilities.ts
```
export const getDeepLink = (path = "") => {
  const scheme = 'my-demo';
  const prefix = global.isAndroid ? `${scheme}://demo/` : `${scheme}://`;
  return prefix + path;
};
```

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by jdnichollsc** [comment]
What version of Android are you testing with?

**Comment by BrothersWar** [comment]
android 8.0.0 In demo app everything is fine. Can this probleme be because my app is angular-nativescript migration and i don't have app-root.xml my page file named game.component.tns.html (analog home-page.xml)

**Comment by jdnichollsc** [comment]
No idea, can you attach a repository to debug this issue?

**Comment by BrothersWar** [comment]
I figured it out. The problem was that my Android Manifest was in (Android/src/res) folder instead of (Android/src) folder. There is correct location on the screen.
![image](https://user-images.githubusercontent.com/60742174/112686550-2789bf00-8e87-11eb-987f-cee9479a7d6e.png)
