### ISSUE TITLE
Android Crash - TypeError: Cannot read property 'resources' of undefined

### ISSUE THREAD

**Issue by keithoys** [proyecto26/nativescript-inappbrowser#64]
### Which platform(s) does your issue occur on?
- Android 9
- Device: Samsung S8+

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.8.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s):
`"tns-ios": {
      "version": "6.5.2"
    },
    "tns-android": {
      "version": "6.5.3"
    }`
- Plugin(s):
`"dependencies": {
        "nativescript-inappbrowser": "^3.0.2",
   }`

### Please, tell us how to recreate the issue in as much detail as possible. 
I'm on **Nativescript Vue**. Running `tns run android`, app crashes with the following error:

```
Error calling module function
System.err: TypeError: Cannot read property 'resources' of undefined
```

![2021-03-25 at 1 29 PM](https://user-images.githubusercontent.com/7553961/112423813-4c3e4380-8d6e-11eb-9c70-6659cfe1888a.png)

Implementation-wise, it's simply the same as shown in demo. 

```
import { InAppBrowser } from 'nativescript-inappbrowser';
...
this.openMyLink();
...
public async openMyLink() {
  try {
    const url = 'https://google.com'
    if (await InAppBrowser.isAvailable()) {
      const result = await InAppBrowser.open(url, {
        // iOS Properties
        dismissButtonStyle: 'done',
        preferredBarTintColor: '#f4f6fb',
        preferredControlTintColor: '#000',
        readerMode: false,
        animated: true,
        modalPresentationStyle: 'fullScreen',
        modalTransitionStyle: 'coverVertical',
        modalEnabled: true,
        enableBarCollapsing: false,

        // Android Properties
        showTitle: true,
        toolbarColor: '#f4f6fb',
        secondaryToolbarColor: '#000',
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false,

        animations: {
          startEnter: 'slide_in_right',
          startExit: 'slide_out_left',
          endEnter: 'slide_in_left',
          endExit: 'slide_out_right'
        },
        hasBackButton: true,
        browserPackage: '',
        showInRecents: false
      });
      console.log("--->", result);
    }
    else {
      utils.openUrl(url);
    }
  }
  catch(error) {
    console.log("--->", error);
  }
}

**Comment by jdnichollsc** [comment]
What version of `@nativescript/core` are you using?

**Comment by keithoys** [comment]
Hello @jdnichollsc I'm not using `@nativescript/core`. Instead, I'm using  `"tns-core-modules": "^6.5.2",`

**Comment by jdnichollsc** [comment]
Sorry, you need to use a previous version of this library
