### ISSUE TITLE
Load local HTML files

### ISSUE THREAD

**Issue by Izrab** [proyecto26/nativescript-inappbrowser#7]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
How do I load local HTML files? Those inside app/ directory.

### Which platform(s) does your issue occur on?
- Both 
- Device

**Comment by jdnichollsc** [comment]
Only http and https protocols are supported, you need to use WebView instead 👍

**Comment by Izrab** [comment]
@jdnichollsc So it is impossible to load local files?! No, with webView I don't get full functionality of CustomTabs and SafariServices...
Anyways, thanks for such quick response.

**Comment by jdnichollsc** [comment]
**SafariViewController** only support http and https protocols as you can see here https://stackoverflow.com/a/39869386/1532821

**Comment by jdnichollsc** [comment]
The same with Android CustomTabs => https://stackoverflow.com/a/33277933/1532821
