### ISSUE TITLE
[iOS] InAppBrowser is reverting the statusbar color settings after closing it

### ISSUE THREAD

**Issue by ejlocop** [proyecto26/nativescript-inappbrowser#70]
### Which platform(s) does your issue occur on?
- iOS 7.2.0

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.2.0
- Cross-platform modules: 7.0.0
- Runtime(s): 7.2.0
- Plugin(s): 
```
"dependencies": {
    "@nativescript-community/systemui": "^1.1.7",
    "@nativescript/core": "7.0.0",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/local-notifications": "^5.0.3",
    "@nativescript/webpack": "3.0.0",
    "@nota/nativescript-webview-ext": "^8.0.0",
    "@owen-it/nativescript-uuid": "0.0.4",
    "nativescript-inappbrowser": "^3.0.2",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-vue": "~2.8.0",
    "nativescript-webview-interface": "^1.4.4",
    "vuex": "^3.5.1"
},
"devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.2.0",
    "@nativescript/types": "7.0.0",
    "@types/node": "^14.11.2",
    "@vue/test-utils": "^1.1.3",
    "axios": "^0.21.1",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.1.0",
    "dotenv": "^8.2.0",
    "jest": "^26.6.3",
    "nativescript-vue-template-compiler": "~2.8.0",
    "node-sass": "^4.14.1",
    "typescript": "^4.0.3",
    "vue-jest": "^3.0.7",
    "vue-loader": "15.9.3",
    "vue": "^2.6.12"
},
```

### Please, tell us how to recreate the issue in as much detail as possible. 
- set the status bar color for the iOS app (ie: blue)
- install the inappbrowser plugin
- open a link via inappbrowser
- close it and then notice the statusbar color reverting to the original color/theme (light/dark)

### Is there any code involved? 
_main.ts_
![image](https://user-images.githubusercontent.com/12082880/118214740-ea16da80-b4a2-11eb-88c9-188cb4f923ff.png)

_template_
![image](https://user-images.githubusercontent.com/12082880/118214774-fac75080-b4a2-11eb-9d3b-c7fdbe4217ab.png)

_inappbrowser code block_
![image](https://user-images.githubusercontent.com/12082880/118214821-10d51100-b4a3-11eb-87ed-48a34397eb16.png)

Screenshots of my app doing the steps above.
![image](https://user-images.githubusercontent.com/12082880/118214911-3235fd00-b4a3-11eb-8825-18320a146ebf.png)

**Comment by jdnichollsc** [comment]
Any pull request is welcome! <3

**Comment by jdnichollsc** [comment]
Hello mate, please check the README of the new version [3.1.0](https://github.com/proyecto26/nativescript-inappbrowser/releases/tag/v3.1.0) 👍
