### ISSUE TITLE
Please fix documentation for Android 11

### ISSUE THREAD

**Issue by Yambr** [proyecto26/nativescript-inappbrowser#71]
For android 11 you need fix AndroidManifest.xml

https://stackoverflow.com/questions/62345805/namenotfoundexception-when-calling-getpackageinfo-on-android-11

for example

`
<manifest ...>
     ...
     <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
     ...
     <application ...>
     ...
</manifest>
`

**Comment by jdnichollsc** [comment]
Any pull request is welcome! 🤗

**Comment by jdnichollsc** [comment]
Hello mate, please check the new version [3.1.0](https://github.com/proyecto26/nativescript-inappbrowser/releases/tag/v3.1.0) 👍
