### ISSUE TITLE
[openAuth] redirectUrl parameter

### ISSUE THREAD

**Issue by uderline** [proyecto26/nativescript-inappbrowser#72]
Hi everyone !

I wanted to talk about the `openAuth`'s parameter

### Possible issue for iOS users
I just updated XCode to 12.5 - iOS 14.5 - and a small change has appeared for apple devices.
On iOS, putting a `:` or a `/` in the `redirectUrl` argument of the `openAuth` method will result with an error.

`CONSOLE ERROR: Issue when disconnecting the user Error: The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".`

Basically you can't write `schema://host.com`. This is due to `ASWebAuthenticationSession` which only accepts a schema. Link to a post answered by an Apple engineer: https://developer.apple.com/forums/thread/679251

So ... Maybe we should rename the parameter and/or send a warning saying that it comes from the openAuth method. Also update the doc ?

### Dummy value when using Auth0 service
By the way, I use the Auth0 service and the request to send is:

```ts
const authorizeUrl = 'https://{tenant}.auth0.com/authorize?audience={audience}&' +
            'scope=offline_access&' +
            'response_type=code&' +
            'client_id={client_id}&' +
            'redirect_uri=' + redirectUri + '&' +
            'code_challenge=' + challenge + '&' +
            'code_challenge_method=S256';

  const response: AuthSessionResult = await InAppBrowser.openAuth(authorizeUrl, 'dummy', {
      // iOS Properties
      ephemeralWebSession: true,
      // Android Properties
      showTitle: false,
      enableUrlBarHiding: true,
      enableDefaultShare: false,
      forceCloseOnRedirection: true,
  });
```

`await InAppBrowser.openAuth(authorizeUrl, 'dummy')` see here I use the value "dummy" and it still works like a charm ! Is this normal ? 😮

It seems like Auth0 actually deals with redirect uri so is it relevant to have redirectUrl mandatory ? I know `ASWebAuthenticationSession.initWithURLCallbackURLSchemeCompletionHandler` asks for it though maybe this method can give a dummy value instead like this:
```ts
// InAppBrowser.ios.ts
this.authSession = (
  Utils.ios.MajorVersion >= 12 ? ASWebAuthenticationSession : SFAuthenticationSession
).alloc().initWithURLCallbackURLSchemeCompletionHandler(
  url,
  redirectUrl ?? "dummy",
```

All this is for the iOS vision but I keep in mind Android. For the dummy value, this also works with Android.

Before I forget, I'm using Nativescript 8 😉 All this has been tested on emulators.

I know PRs are always appreciated but I'd like your opinion on all this before I do anything

Regards,

**Comment by jdnichollsc** [comment]
With this new iOS version is required to use `encodeURIComponent(redirectUrl)` in the meantime :)

**Comment by jdnichollsc** [comment]
Hello mate, please check the new version [3.1.0](https://github.com/proyecto26/nativescript-inappbrowser/releases/tag/v3.1.0) 👍
