### ISSUE TITLE
3.1.0 seems to not be compiled correctly

### ISSUE THREAD

**Issue by jcassidyav** [proyecto26/nativescript-inappbrowser#77]
I'm getting then following on android:

ReferenceError: NativeClass is not defined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: ReferenceError: NativeClass is not defined
System.err: File: (file: node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:87:0)
System.err:
System.err: StackTrace:
System.err: ./node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js(file: node_modules\nativescript-inappbrowser\ChromeTabsManagerActivity.js:87:0)
System.err:     at __webpack_require__(file: src\webpack\bootstrap:19:0)

This typically happens when the plugin is built, but ``` ts-patch install``` has not been executed.

### Which platform(s) does your issue occur on?
- Android emulator

### Please, provide the following version numbers that your issue occurs with:

√ Your ANDROID_HOME environment variable is set and points to correct directory.
√ Your adb from the Android SDK is correctly installed.
√ The Android SDK is installed.
√ A compatible Android SDK for compilation is found.
√ Javac is installed and is configured properly.
√ The Java Development Kit (JDK) is installed and is configured properly.
√ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
√ Getting NativeScript components versions information...
√ Component nativescript has 8.0.2 version and is up to date.
√ Component @nativescript/core has 8.0.8 version and is up to date.
√ Component @nativescript/ios has 8.0.0 version and is up to date.
√ Component @nativescript/android has 8.0.0 version and is up to date.

### Please, tell us how to recreate the issue in as much detail as possible. 
Just trying to launch the app will trigger it.

**Comment by jdnichollsc** [comment]
Hey mate, thanks for reporting this issue! Can you validate the new version 3.1.1 please?

Thanks for your collaboration!

**Comment by jcassidyav** [comment]
3.1.2 is fine for me on android, thanks for the quick response.
