### ISSUE TITLE
does not work, ERROR

### ISSUE THREAD

**Issue by Izrab** [proyecto26/nativescript-inappbrowser#8]
I just created a new project in NS Sidekick (**core** XML/TypeScript), and added this plugin, and built app on my Android device, copied and paste the demo page files, but this when I open my app, this ERROR message appears 
![67127477_2342535762627551_470824652973801472_n](https://user-images.githubusercontent.com/22328131/61978241-9a051600-afa5-11e9-8793-47a2577fcd4f.jpg)

### Which platform(s) does your issue occur on?
- Android
- Android version 9
- Real device. Samsung Galaxy A70 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.2
- Cross-platform modules: 6.0.0
- Runtime(s):  `"tns-android"` version 6.0.0 
- Plugin(s): using latest core-tns-modules, core-theme, typescript, and dev-webpack, all appear latest in Sidekick GUI, and obviously InAppBrowser.

EDIT:
Nothing works, each time new build and I try new ways, new kind of error messages appear, 
once even a dialog opened while taping on the search (from demo), it said something like " cannot build of undefined...". 
Also, I tried to use the code from readme, but the browser does not open, no errors appear, no feedback...

**Comment by jdnichollsc** [comment]
Try the last version v2.0.0 and let me know 👍

**Comment by Izrab** [comment]
@jdnichollsc , Now works **very smoothly and well**... Thanks a lot, this is a very nice and important plugin.
