### ISSUE TITLE
Is there any way to listen to events within the inAppBrowser?

### ISSUE THREAD

**Issue by erodriguezh** [proyecto26/nativescript-inappbrowser#81]
Hi Maintainers,

I have the following question: 
I am using the function _open_ to load a website and I would like to close the InAppBrowser if the website loading returns a network or http error. Is there any way to listen to them?

Thanks a lot.

**Comment by jdnichollsc** [comment]
Hello mate, thanks for reporting this issue

Chrome CustomTabs and SafariViewController don't allow that, from your external page you can redirect the user to the app using deep linking or from your app you can have a listener to detect network changes.

I hope this can help you!
