### ISSUE TITLE
Question - Closing inappbrowser when user lands on a specified webpage

### ISSUE THREAD

**Issue by keithhie** [proyecto26/nativescript-inappbrowser#83]
May I please request some advice to achieve this flow in my corporate Nativescript App:

1. Open my corporate web platform (`mycorp.sg/feedback`) in this inappbrowser
2. User fills up and submits a feedback form
3. After submission to the form, the web platform will redirect to a login page (`mycorp.sg/login`) and when that happens, I need to close the inappbrowser and return to my app

I'm not looking for an access token here - instead, I intend to leverage on `openAuth` simply as a means to close the inappbrowser once a webpage has been reached.

Is that doable?

**Comment by jdnichollsc** [comment]
Sorry, that's not possible, you need to redirect your users to the app again from that web page using deep linking (server side redirection)

**Comment by keithhie** [comment]
@jdnichollsc Could you shed some light on how this can be done? Also, is there any callback inappbrowser provides to check which URL is currently accessed so perhaps I can `close` the inappbrowser manually once a specified URL has been reached.

**Comment by jdnichollsc** [comment]
That's not supported by Android CustomTabs or SafariViewController, if you need to check the current url the only way is using WebView instead.
For more details about deep linking redirection: https://www.appsflyer.com/resources/guides/deep-linking-for-mobile-marketers/

Best,
Juan
