### ISSUE TITLE
Use of Use of the broad package (App) visibility (QUERY_ALL_PACKAGES) permission being restricted by Google

### ISSUE THREAD

**Issue by jcassidyav** [proyecto26/nativescript-inappbrowser#84]
Google are restricting the use of QUERY_ALL_PACKAGES in apps from this year. 

See:  https://support.google.com/googleplay/android-developer/answer/10158779?hl=en#zippy=%2Cpermitted-uses-of-the-query-all-packages-permission%2Cexceptions%2Cinvalid-uses 

Our app has been flagged in the store as having this permission set, and we traced it back to inappbrowser.

i.e. 	<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" /> in the AndroidManifest.xml file.

I built the plugin locally removing this line and it appears to work correctly for the demo and my simple scenarios on api 30/32 emulators, is this required for different scenarios, or have i missed something in my testing?

**Comment by jcassidyav** [comment]
That's fantastic! Thank you.

**Comment by edusperoni** [comment]
Hello!

Any updates on this?

**Comment by tommag21** [comment]
Hi everyone, I am in dire need of a fix for this issue and found [this fork](https://github.com/farfromrefug/nativescript-inappbrowser) by farfromrefuge, who maintains a lot of NativeScript plugins. It includes the fix for this issue plus some minor optimization and the author can ask merge it into master.

**Comment by jdnichollsc** [comment]
Hello folks, I'm planning to publish a new version today with new options, thank you for your patience!

**Comment by jdnichollsc** [comment]
@tommag21 what optimizations are you referring to? 🤔

**Comment by jdnichollsc** [comment]
> Hi everyone, I am in dire need of a fix for this issue and found [this fork](https://github.com/farfromrefug/nativescript-inappbrowser) by farfromrefuge, who maintains a lot of NativeScript plugins. It includes the fix for this issue plus some minor optimization. The author can merge it into master.

I remember I closed his [PR](https://github.com/proyecto26/nativescript-inappbrowser/pull/80) because he wasn't very willing to have a simple discussion from a new issue before making changes to the repository, which is very important when working in a community :)

**Comment by tommag21** [comment]
> @tommag21 what optimizations are you referring to? 🤔
I don't know, just based on the commits' name.

> I remember I closed his [PR](https://github.com/proyecto26/nativescript-inappbrowser/pull/80) because he wasn't very willing to have a simple discussion from a new issue before making changes to the repository, which is very important when working in a community :)
I'm sorry, I did not know that.

**Comment by woeckener** [comment]
Hey guys, just wanted to ask respectfully, if there is still work being done here or if and when we can count on a new version. Thank you!

**Comment by dannyknowlton** [comment]
> Hello folks, I'm planning to publish a new version today with new options, thank you for your patience!

Hi @jdnichollsc, how's it going with this update?

**Comment by jdnichollsc** [comment]
Hello folks, excuse me for the delay
My Mac stopped working, I'm planning to release a new version as soon as possible, sorry for the inconvenience 🙏 

Regards,
Juan

**Comment by alexxxo1985** [comment]
Any updates on this?

**Comment by kandangit** [comment]
Hello, We also have the issue and need a fix in the short term , before July 20th. For now we will resort to having an external browser opening the URL and removing the plugin dependency.
Many thanks.

**Comment by empresarrollo** [comment]
We too, have the july 20 deadline. I think we will end up using a modal with a webview or something like that...

**Comment by edusperoni** [comment]
@empresarrollo At this point I'd recommend switching to `@akylas/nativescript-inappbrowser` as it seems that was already fixed on his fork

**Comment by jasonfrasch** [comment]
> @empresarrollo At this point I'd recommend switching to `@akylas/nativescript-inappbrowser` as it seems that was already fixed on his fork

This is what we ended up doing, too.

**Comment by jdnichollsc** [comment]
Sorry for the delay folks, we fixed some issues like this one and added new options in the new [Release 3.2.0](https://github.com/proyecto26/nativescript-inappbrowser/releases/tag/v3.2.0), thanks for your thank you for your patience!

@jcassidyav @edusperoni thanks folks for your contributions! <3

**Comment by jdnichollsc** [comment]
BTW, we are supporting NativeScript 8! 👍
