### ISSUE TITLE
Response type cancel on device during live sync

### ISSUE THREAD

**Issue by uderline** [proyecto26/nativescript-inappbrowser#85]
Hi !

### The issue
During development, when running `ns run|debug ios`, I'm having issues with the `openAuth` function. It always returns a response `{type: cancel}`.

### Config and how to reproduce
My config:
- Mac M1
- NS 8
- iPhone 11 / iOS 15

I managed to reproduce the bug on the demo app (that I needed to upgrade to NS 8 because it wouldn't build otherwise).
These are the following steps:
- Start the app
- Click on "Try deep linking"
- Wait for the alert message `Response {type: cancel}`

### My investigation  
I tried to go to the source of the problem and I found out that `ASWebAuthenticationSession` needs some kind of context which is given by the method `InAppBrowserModule::presentationAnchorForWebAuthenticationSession`.

Only problem, the value returned by this method is `null` (i.e. `UIApplication.sharedApplication.keyWindow` is `null`).

Next step, Google the error and this is what I found:
- https://developer.apple.com/forums/thread/695932 (deprecation)
> [UIApplication keyWindow] is deprecated and shouldn't be used for apps on iOS 15.

- https://developer.apple.com/forums/thread/659682 (possible fix)
> You probably have to change as follows:
> `UIApplication.shared.keyWindow`
> with
> UIApplication.shared.windows[0]

So I tried replacing `keyWindow` by `windows[0]` and it works !
Considering that `keyWindow` is deprecated, even if there are no errors when the app is built and deployed, maybe it would be time to update this anyway.

### Questions
- Should this be considered as a good fix ? (Not an iOS programer)
- Would you like a PR upgrading the demo to NS 8 ? 

Regards,

**Comment by jdnichollsc** [comment]
@uderline hello mate, sorry for the delay

Thanks for reporting this issue, can you debug this [PR](https://github.com/proyecto26/nativescript-inappbrowser/pull/100) and let me know? any pull request or comments are always really appreciated! <3
