### ISSUE TITLE
A type error

### ISSUE THREAD

**Issue by Izrab** [proyecto26/nativescript-inappbrowser#9]
What is this typescript error
![image](https://user-images.githubusercontent.com/22328131/61978424-1bf53f00-afa6-11e9-93d1-dab53f6745fa.png)

Details: Just installed inAppBrowser and playing with it, all today and all latest of everything.

**Comment by jdnichollsc** [comment]
the version with these new properties is not published as you can see here https://github.com/proyecto26/nativescript-inappbrowser/blob/master/CHANGELOG.md#unreleased

**Comment by jdnichollsc** [comment]
Check the last version 2.0.0 mate and let me know 👍
